/// Generated by AssetsRefGenerator on 2020/04/29
class Res {
  static const String icon_cart = "assets/images/icon_cart.png";
  static const String icon_message = "assets/images/icon_message.png";
  static const String icon_order = "assets/images/icon_order.png";
  static const String icon_scan = "assets/images/icon_scan.png";
  static const String image_placeholder = "assets/images/image_placeholder.png";
  static const String logo = "assets/images/logo.png";
  static const String mine_header = "assets/images/mine_header.jpg";
  static const String network_error = "assets/images/network_error.png";
  static const String page_empty = "assets/images/page_empty.png";
  static const String place_avatar = "assets/images/place_avatar.jpeg";
}
